<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>incollectionDropdown</name>
   <tag></tag>
   <elementGuidId>8d6a1276-719a-4bee-b9e8-e02258226795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectCollections > div.p-multiselect-trigger > span.p-multiselect-trigger-icon.pi.pi-chevron-down.p-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectCollections']/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-trigger-icon pi pi-chevron-down p-c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectCollections&quot;)/div[@class=&quot;p-multiselect-trigger&quot;]/span[@class=&quot;p-multiselect-trigger-icon pi pi-chevron-down p-c&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectCollections']/div[4]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/span</value>
   </webElementXpaths>
</WebElementEntity>
