<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bookmark_p-rating-icon p-rating-cancel pi pi-ban</name>
   <tag></tag>
   <elementGuidId>3900cbf8-c2ad-46fc-a18d-c7dcd12710d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-rating-icon.p-rating-cancel.pi.pi-ban</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_26']/div[2]/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-rating-icon p-rating-cancel pi pi-ban</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_26&quot;)/div[@class=&quot;p-dialog-content&quot;]/div[1]/div[2]/div[@class=&quot;p-rating&quot;]/span[@class=&quot;p-rating-icon p-rating-cancel pi pi-ban&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_26']/div[2]/div/div[2]/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
