<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bookmark_p-rating-icon 3</name>
   <tag></tag>
   <elementGuidId>65ac9e4b-e207-425a-b586-a0d0a277b302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_26 > div.p-dialog-content > div:nth-child(1) > div:nth-child(2) > div.p-rating > span:nth-child(4)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[2]/div[2]/div[2]/div[3]/div[2]/div[3]/div/div[2]/div[1]/div[2]/div[1]/span[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div[2]/div[2]/div[3]/div[2]/div[3]/div/div[2]/div[1]/div[2]/div[1]/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-rating-icon pi pi-star</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[2]/div[2]/div[2]/div[3]/div[2]/div[3]/div/div[2]/div[1]/div[2]/div[1]/span[4]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_26']/div[2]/div/div[2]/div/span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[4]</value>
   </webElementXpaths>
</WebElementEntity>
